# Lecture 1 demo code

#### 2022-06-24

### Installing cowsay

```{r}
install.packages("cowsay")
```

Use `::` to access the `say` function in the `cowsay` package.

```{r}
cowsay::say("Welcome to PSTAT 10!", by = "cow")
```

Or load the `cowsay` package so that all functions are available.

```{r}
library(cowsay)
say("Now we don't need the double colon operator", by = "cow")
```

Uninstall a package:

```{r}
remove.packages("cowsay")
```

### R as a calculator (slide 22)

```{r}
(5^7 - 2 * sqrt(4)) / log(100, base = 2)
```

### Vectors (slide 34)

1.  

```{r}
x <- c(1, 3, 5, 6)
scores <- c(8, 7, 8, 10, 5)
```

2.  

```{r}
mean(scores)
```

```{r}
sum(scores) / length(scores)
```

It is better to call `length` in the denominator instead of hard-code
the number 5. This is because if we add more scores, the denominator
would still be right.

3.  

```{r}
median(scores)
```

4.  

```{r}
names(scores) <- c("Bob", "Alice", "Alex", "Juan", "Amy")
scores
```

5.  

```{r}
scores[2]
```

```{r}
scores["Alice"]
```

6.  

```{r}
scores[c("Amy", "Alice")]
```

7.  

```{r}
scores[-5]
```
